//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanrCloudService
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public @event()
        {
            this.collaborators = new HashSet<collaborator>();
            this.user_attending = new HashSet<user_attending>();
            this.notifications = new HashSet<notification>();
            this.suggestions = new HashSet<suggestion>();
            this.tasks = new HashSet<task>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int user_id { get; set; }
        public string time { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string code { get; set; }
        public int type { get; set; }
        public int invite_type { get; set; }
        public string coordinates { get; set; }
        public string photo { get; set; }
        public string venue { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<collaborator> collaborators { get; set; }
        public virtual ICollection<user_attending> user_attending { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<notification> notifications { get; set; }
        public virtual ICollection<suggestion> suggestions { get; set; }
        public virtual ICollection<task> tasks { get; set; }
    }
}
