//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanrCloudService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlanrDBEntities1 : DbContext
    {
        public PlanrDBEntities1()
            : base("name=PlanrDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<collaborator> collaborators { get; set; }
        public DbSet<connection> connections { get; set; }
        public DbSet<date_suggestions> date_suggestions { get; set; }
        public DbSet<@event> events { get; set; }
        public DbSet<idea_suggestions> idea_suggestions { get; set; }
        public DbSet<notification> notifications { get; set; }
        public DbSet<suggestion> suggestions { get; set; }
        public DbSet<task> tasks { get; set; }
        public DbSet<time_suggestions> time_suggestions { get; set; }
        public DbSet<user_attending> user_attending { get; set; }
        public DbSet<user_likes> user_likes { get; set; }
        public DbSet<user_tasks> user_tasks { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<venue_suggestions> venue_suggestions { get; set; }
    }
}
