//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanrCloudService
{
    using System;
    using System.Collections.Generic;
    
    public partial class suggestion
    {
        public suggestion()
        {
            this.date_suggestions = new HashSet<date_suggestions>();
            this.idea_suggestions = new HashSet<idea_suggestions>();
            this.user_likes = new HashSet<user_likes>();
            this.time_suggestions = new HashSet<time_suggestions>();
            this.venue_suggestions = new HashSet<venue_suggestions>();
        }
    
        public int id { get; set; }
        public int event_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime created { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<date_suggestions> date_suggestions { get; set; }
        public virtual @event @event { get; set; }
        public virtual ICollection<idea_suggestions> idea_suggestions { get; set; }
        public virtual ICollection<user_likes> user_likes { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<time_suggestions> time_suggestions { get; set; }
        public virtual ICollection<venue_suggestions> venue_suggestions { get; set; }
    }
}
