//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanrCloudService
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public task()
        {
            this.user_tasks = new HashSet<user_tasks>();
            this.user_tasks1 = new HashSet<user_tasks>();
        }
    
        public int id { get; set; }
        public int event_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime created { get; set; }
        public string description { get; set; }
        public System.DateTime deadline { get; set; }
        public int type { get; set; }
        public int priority { get; set; }
    
        public virtual @event @event { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<user_tasks> user_tasks { get; set; }
        public virtual ICollection<user_tasks> user_tasks1 { get; set; }
    }
}
