//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanrCloudService
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_likes
    {
        public int user_id { get; set; }
        public int suggestion_id { get; set; }
        public int type { get; set; }
    
        public virtual suggestion suggestion { get; set; }
        public virtual user user { get; set; }
    }
}
