//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanrCloudService
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_tasks
    {
        public int id { get; set; }
        public int task_id { get; set; }
        public int user_id { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> completed_on { get; set; }
    
        public virtual task task { get; set; }
        public virtual task task1 { get; set; }
    }
}
