//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanrCloudService
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.collaborators = new HashSet<collaborator>();
            this.connections = new HashSet<connection>();
            this.events = new HashSet<@event>();
            this.notifications = new HashSet<notification>();
            this.suggestions = new HashSet<suggestion>();
            this.tasks = new HashSet<task>();
            this.user_attending = new HashSet<user_attending>();
            this.user_likes = new HashSet<user_likes>();
            this.notifications1 = new HashSet<notification>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string fb_token { get; set; }
        public string color_code { get; set; }
    
        public virtual ICollection<collaborator> collaborators { get; set; }
        public virtual ICollection<connection> connections { get; set; }
        public virtual ICollection<@event> events { get; set; }
        public virtual ICollection<notification> notifications { get; set; }
        public virtual ICollection<suggestion> suggestions { get; set; }
        public virtual ICollection<task> tasks { get; set; }
        public virtual ICollection<user_attending> user_attending { get; set; }
        public virtual ICollection<user_likes> user_likes { get; set; }
        public virtual ICollection<notification> notifications1 { get; set; }
    }
}
