//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanrCloudService
{
    using System;
    using System.Collections.Generic;
    
    public partial class venue_suggestions
    {
        public int id { get; set; }
        public int suggestion_id { get; set; }
        public string coordinates { get; set; }
        public string photo { get; set; }
        public string venue { get; set; }
        public string address { get; set; }
        public string description { get; set; }
    
        public virtual suggestion suggestion { get; set; }
    }
}
